name: Sitemap Ping Schedule

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  cron:
    name: Cron

    runs-on: ubuntu-latest

    steps:
      - run: curl https://www.google.com/ping\?sitemap\=https://www.knoticle.app/sitemap.xml
